# Generated by Django 3.2.9 on 2021-12-06 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('shipping_vendor', models.CharField(blank=True, max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=200)),
                ('work_order', models.CharField(blank=True, max_length=200)),
                ('sales_order', models.CharField(blank=True, max_length=200)),
                ('qnt', models.CharField(max_length=200)),
                ('serial_numbers', models.CharField(max_length=2000)),
                ('processed', models.BooleanField(default=False)),
                ('palletized', models.BooleanField(default=False)),
                ('width', models.CharField(max_length=200)),
                ('length', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_processed', models.DateTimeField()),
                ('date_shipping', models.DateField()),
            ],
        ),
    ]
