# Generated by Django 3.2.9 on 2021-12-09 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Project', '0003_auto_20211206_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Final_Project.client'),
        ),
    ]
